import { Package } from "@/types";
import {
  Award,
  Bulb,
  Check,
  HeartHandshake,
  Settings,
  Tree,
  Users,
} from "tabler-icons-react";

export const ServicesData = [
  {
    title: "PV SYSTEM DESIGN",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "FULL INSTALLATION",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "PROCUREMENT",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "MAINTENANCE",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "PROJECT MANAGEMENT",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "PROJECT CONSULTATION",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "TROUBLESHOOTING AND TECHNICAL SUPPORT",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "EXCLUSIVE MENTORING",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "TRAINING AND SEMINARS",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
];

export const JFLTeamMembers = [
  {
    imageUrl: "/team-jf.jpg",
    name: "JF Legaspi",
    position: "CEO / Founder",
    description: `"A visionary leader with extensive experience in the global solar industry, committed to advancing renewable energy solutions in the Philippines."`,
  },
  {
    imageUrl: "/team-john.jpg",
    name: "John Bergueles",
    position: "CCO (Sales and Marketing)",
    description: `"A dynamic strategist driving business growth through effective sales initiatives and impactful marketing campaigns."`,
  },
  {
    imageUrl: "/team-jay.jpg",
    name: "Jay Escander",
    position: "CTO",
    description: `"An innovative technical expert specializing in designing and implementing efficient and reliable solar PV systems."`,
  },
];

export const FeaturesData = [
  {
    title: "European Quality Standards",
    description: `We adhere to stringent European quality benchmarks, ensuring superior workmanship and durable solutions.`,
    icon: Award,
  },
  {
    title: "Expertise and Experience",
    description: `Our team brings international experience and deep technical knowledge, guaranteeing innovative and effective solutions.`,
    icon: Bulb,
  },
  {
    title: "Comprehensive Services",
    description: `From procurement to maintenance, we offer end-to-end services tailored to meet diverse energy needs.`,
    icon: Settings,
  },
  {
    title: "Customer-Centric Approach",
    description: `We prioritize our clients' satisfaction, offering personalized services and ongoing support throughout your solar journey.`,
    icon: Users,
  },
  {
    title: "Technical Support for DIY Enthusiasts",
    description: `Our team brings international experience and deep technical knowledge, guaranteeing innovative and effective solutions.`,
    icon: HeartHandshake,
  },
  {
    title: "Commitment to Sustainability",
    description: `Our solutions are designed to promote environmental stewardship and contribute to a sustainable future.`,
    icon: Tree,
  },
];

export const HybridPackagesData: Package[] = [
  {
    id: "hybrid-6kw",
    title: "6kW Hybrid On/Off-Grid Package",
    size: "6kW",
    description: (
      <ul className="flex flex-col items-center">
        <li className="flex items-center gap-1">
          <Check size={18} /> 6kW Hybrid Inverter
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 10kWh LiFePO4 Battery
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 7.7kWp Solar Panels
        </li>
      </ul>
    ),
    inverter: "1x 6kW Lux Power or Deye Hybrid Inverter",
    battery: "1x 200Ah ATE or LVFU LiFePO4 Battery (10kWh)",
    panel: "14pcs 550W Seraphim or AE Solar Panels (7.7kWp)",
    mounting: "Complete Mounting System (End, Mid-Clamps & Railings)",
    safetyDevices:
      "AC and Safety Devices (MCB, PV Iso Switch, SPD, ATS & MCCB)",
    cables: "Cables and Wires (PV Cable, Battery Cable & THHN Wire)",
    accessories:
      "Accessories (Cable Tray, Enclosure Box, MC4 Connectors, Ground Rod, Flexible Conduit)",
    annualProd: "11,000 kWh",
    estimatedROI: "2.5 - 3 yrs",
    priceDIY: "₱300,000",
    priceWithInstallation: "₱360,000",
    discountedPriceDIY: "₱250,000",
    discountedPriceWithInstallation: "₱310,000",
    imageUrl: "/hybrid-6kw.png",
    buttonText: "View Details",
    redirectLinkDIY: "/packages/diy/hybrid-6kw?",
    redirectLinkInstallation: "/packages/installation/hybrid-6kw?",
    quoteLink: "/quotation?type=hybrid&system=6",
  },
  {
    id: "hybrid-8kw",
    size: "8kW",
    title: "8kW Hybrid On/Off-Grid Package",
    annualProd: "12,500 kWh",
    description: (
      <ul className="flex flex-col items-center">
        <li className="flex items-center gap-1">
          <Check size={18} /> 8kW Hybrid Inverter
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 15kWh LiFePO4 Battery
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 8.8kWp Solar Panels
        </li>
      </ul>
    ),
    inverter: "1x 8kW Lux Power or Deye Hybrid Inverter",
    battery: "1x 300Ah ATE or Wipuvo LiFePO4 Battery (15kWh)",
    panel: "16pcs 550W Seraphim or AE Solar Panels (8.8kWp)",
    mounting: "Complete Mounting System (End, Mid-Clamps & Railings)",
    safetyDevices:
      "AC and Safety Devices (MCB, PV Iso Switch, SPD, ATS & MCCB)",
    cables: "Cables and Wires (PV Cable, Battery Cable & THHN Wire)",
    accessories:
      "Accessories (Cable Tray, Enclosure Box, MC4 Connectors, Ground Rod, Flexible Conduit)",
    estimatedROI: "2.3 - 3 yrs",
    priceDIY: "₱400,000",
    priceWithInstallation: "₱480,000",
    discountedPriceDIY: "₱350,000",
    discountedPriceWithInstallation: "₱430,000",
    imageUrl: "/hybrid-8kw.png",
    buttonText: "View Details",
    redirectLinkDIY: "/packages/diy/hybrid-8kw?",
    redirectLinkInstallation: "/packages/installation/hybrid-8kw?",
    quoteLink: "/quotation?type=hybrid&system=8",
  },
  {
    id: "hybrid-10kw",
    title: "10kw Hybrid On/Off-Grid Package",
    size: "10kW",
    description: (
      <ul className="flex flex-col items-center">
        <li className="flex items-center gap-1">
          <Check size={18} /> 10kw Hybrid Inverter
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 15kWh LiFePO4 Battery
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 9.9kWp Solar Panels
        </li>
      </ul>
    ),
    inverter: "1x 10kW Lux Power Hybrid Inverter",
    battery: "1x 300Ah ATE or Wipuvo LiFePO4 Battery (15kWh)",
    panel: "18pcs 550W Seraphim or AE Solar Panels (9.9kWp)",
    mounting: "Complete Mounting System (End, Mid-Clamps & Railings)",
    safetyDevices:
      "AC and Safety Devices (MCB, PV Iso Switch, SPD, ATS & MCCB)",
    cables: "Cables and Wires (PV Cable, Battery Cable & THHN Wire)",
    accessories:
      "Accessories (Cable Tray, Enclosure Box, MC4 Connectors, Ground Rod, Flexible Conduit)",
    annualProd: "14,500 kWh",
    estimatedROI: "2.2 - 3 yrs",
    priceDIY: "₱450,000",
    priceWithInstallation: "₱550,000",
    discountedPriceDIY: "₱400,000",
    discountedPriceWithInstallation: "₱500,000",
    imageUrl: "/hybrid-12kw.png",
    buttonText: "View Details",
    redirectLinkDIY: "/packages/diy/hybrid-10kw?",
    redirectLinkInstallation: "/packages/installation/hybrid-10kw?",
    quoteLink: "/quotation?type=hybrid&system=10",
  },
  {
    id: "hybrid-12kw",
    title: "12kw Hybrid On/Off-Grid Pacakage",
    size: "12kW",
    description: (
      <ul className="flex flex-col items-center">
        <li className="flex items-center gap-1">
          <Check size={18} /> 12kw Hybrid Inverter
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 15kWh LiFePO4 Battery
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 11kWp Solar Panels
        </li>
      </ul>
    ),
    inverter: "1x 12kW Lux Power or Deye Hybrid Inverter",
    battery: "1x 300Ah ATE or Wipuvo LiFePO4 Battery (15kWh)",
    panel: "20pcs 550W Seraphim or AE Solar Panels (11kWp)",
    mounting: "Complete Mounting System (End, Mid-Clamps & Railings)",
    safetyDevices:
      "AC and Safety Devices (MCB, PV Iso Switch, SPD, ATS & MCCB)",
    cables: "Cables and Wires (PV Cable, Battery Cable & THHN Wire)",
    accessories:
      "Accessories (Cable Tray, Enclosure Box, MC4 Connectors, Ground Rod, Flexible Conduit)",
    annualProd: "16,000 kWh",
    estimatedROI: "2.2 - 3 yrs",
    priceDIY: "500,000",
    priceWithInstallation: "620,000",
    discountedPriceDIY: "₱450,000",
    discountedPriceWithInstallation: "₱570,000",
    imageUrl: "/hybrid-12kw.png",
    buttonText: "View Details",
    redirectLinkDIY: "/packages/diy/hybrid-12kw?",
    redirectLinkInstallation: "/packages/installation/hybrid-12kw?",
    quoteLink: "/quotation?type=hybrid&system=12",
  },

  {
    id: "hybrid-16kw",
    title: "16kw Hybrid On/Off-Grid Pacakage",
    size: "16kW",
    description: (
      <ul className="flex flex-col items-center">
        <li className="flex items-center gap-1">
          <Check size={18} /> 16kw Hybrid Inverter
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 15kWh LiFePO4 Battery
        </li>
        <li className="flex items-center gap-1">
          <Check size={18} /> 15.6kWp Solar Panels
        </li>
      </ul>
    ),
    inverter: "1x 16kw Deye Hybrid Inverter",
    battery: "1x 300Ah ATE or Wipuvo LiFePO4 Battery (15kWh)",
    panel: "27pcs 580W Seraphim Solar Panels (15.6kWp)",
    mounting: "Complete Mounting System (End, Mid-Clamps & Railings)",
    safetyDevices:
      "AC and Safety Devices (MCB, PV Iso Switch, SPD, ATS & MCCB)",
    cables: "Cables and Wires (PV Cable, Battery Cable & THHN Wire)",
    accessories:
      "Accessories (Cable Tray, Enclosure Box, MC4 Connectors, Ground Rod, Flexible Conduit)",
    annualProd: "22,800 kWh",
    estimatedROI: "2 - 2.5 yrs",
    priceDIY: "₱570,000",
    priceWithInstallation: "₱730,000",
    discountedPriceDIY: "₱520,000",
    discountedPriceWithInstallation: "₱680,000",
    imageUrl: "/hybrid-16kw.png",
    buttonText: "View Details",
    redirectLinkDIY: "/packages/diy/hybrid-16kw?",
    redirectLinkInstallation: "/packages/installation/hybrid-16kw?",
    quoteLink: "/quotation?type=hybrid&system=16",
  },
];

export const GridTiedPackagesData: Package[] = [
  {
    id: "grid-tied-6kw",
    title: "6kW Grid-tied Package",
    size: "6kW",
    description: `includes a 6kW grid-tied inverter, 6.6kWp solar panels, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting) (Note: Net Metering not Included)`,
    inverter: "1x 6kW Deye Grid-tied Inverter",
    panel: "14pcs 550W AE Solar Panels (7.7kWp)",
    mounting: "Complete Mounting System (End, Mid-Clamps & Railings)",
    safetyDevices:
      "AC and Safety Devices (MCB, PV Iso Switch, SPD, ATS & MCCB)",
    cables: "Cables and Wires (PV Cable, Battery Cable & THHN Wire)",
    accessories:
      "Accessories (Cable Tray, Enclosure Box, MC4 Connectors, Ground Rod, Flexible Conduit)",
    priceDIY: "Starts at ₱160,000",
    priceWithInstallation: "Starts at ₱220,000",
    discountedPriceDIY: "",
    discountedPriceWithInstallation: "",
    imageUrl: "/package-gridtied.png",
    buttonText: "Get a Quote",
    redirectLinkDIY: "/quotation?type=gridtied&system=6kW",
    redirectLinkInstallation: "/quotation?type=gridtied&system=6kW",
    quoteLink: "/quotation?type=gridtied&system=6kW",
  },
  {
    title: "10kW Grid-tied Package",
    size: "10kW",
    description: `includes a 10kW grid-tied inverter, 10.44kWp solar panels, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting) (Note: Net Metering not Included)`,
    priceDIY: "Starts at ₱220,000",
    priceWithInstallation: "Starts at ₱310,000",
    discountedPriceDIY: "",
    discountedPriceWithInstallation: "",
    imageUrl: "/package-gridtied.png",
    buttonText: "Get a Quote",
    redirectLinkDIY: "/quotation?type=gridtied&system=10kW",
    redirectLinkInstallation: "/quotation?type=gridtied&system=10kW",
    quoteLink: "/quotation?type=gridtied&system=10kW",
  },
];

export const HybridInverterProducts = [
  {
    id: "SUN-5K-SG03LP1-EU",
    title: "Deye 5kW Hybrid Inverter Single Phase",
    model: "SUN-5K-SG03LP1-EU",
    srp: "55000",
    installer: "51000",
    size: "5kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-5K-SG03LP1-EU",
    maxPower: "6500",
    maxVoltage: "500",
    startUp: "125",
    ratedVoltage: "370",
    maxCurrent: "13+13",
    maxIsc: "17+17",
    mppt: "2/1+1",
    dimensions: "330×580×232",
    weight: "25",
    datasheet:
      "https://drive.google.com/file/d/1CyYLreTsiGQJpGiqV6fHQXowA3xS6H4r/view?usp=sharing",
  },
  {
    id: "SUN-6K-SG03LP1-EU",
    title: "Deye 6kW Hybrid Inverter Single Phase",
    model: "SUN-6K-SG03LP1-EU",
    srp: "56000",
    installer: "53000",
    size: "6kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-6K-SG03LP1-EU",
    maxPower: "7800",
    maxVoltage: "500",
    startUp: "125",
    ratedVoltage: "370",
    maxCurrent: "13+13",
    maxIsc: "17+17",
    mppt: "2/1+1",
    dimensions: "330×580×232",
    weight: "25",
    datasheet:
      "https://drive.google.com/file/d/1CyYLreTsiGQJpGiqV6fHQXowA3xS6H4r/view?usp=sharing",
  },
  {
    id: "SUN-8K-SG01LP1-EU",
    title: "Deye 8kW Hybrid Inverter Single Phase",
    model: "SUN-8K-SG01LP1-EU",
    srp: "87000",
    installer: "85000",
    size: "8kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-8K-SG01LP1-EU",
    maxPower: "10400",
    maxVoltage: "500",
    startUp: "125",
    ratedVoltage: "370",
    maxCurrent: "26+26",
    maxIsc: "34+34",
    mppt: "2/2+2",
    dimensions: "420×670×233",
    weight: "30",
    datasheet:
      "https://drive.google.com/file/d/1QrpvwhggEWb4vu8NI7lfQGtkCtQgqsFr/view?usp=drive_link",
  },
  {
    id: "SUN-12K-SG01LP1-EU",
    title: "Deye 12kW Hybrid Inverter Single Phase",
    model: "SUN-12K-SG01LP1-EU",
    srp: "145000",
    installer: "130000",
    size: "12kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-12K-SG01LP1-EU",
    maxPower: "24000",
    maxVoltage: "500",
    startUp: "125",
    ratedVoltage: "370",
    maxCurrent: "26+26+26",
    maxIsc: "44+44+44",
    mppt: "3/2+2+2",
    dimensions: "464×763×282",
    weight: "52",
    datasheet:
      "https://drive.google.com/file/d/132cL3o0V_ojNmkpS_1ZuJJVocea8LqbU/view?usp=sharing",
  },
  {
    id: "SUN-16K-SG01LP1-EU",
    title: "Deye 16kW Hybrid Inverter Single Phase",
    model: "SUN-16K-SG01LP1-EU",
    srp: "160000",
    installer: "150000",
    size: "16kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-16K-SG01LP1-EU",
    maxPower: "32000",
    maxVoltage: "500",
    startUp: "125",
    ratedVoltage: "370",
    maxCurrent: "26+26+26",
    maxIsc: "44+44+44",
    mppt: "3/2+2+2",
    dimensions: "464×763×282",
    weight: "52",
    datasheet:
      "https://drive.google.com/file/d/132cL3o0V_ojNmkpS_1ZuJJVocea8LqbU/view?usp=sharing",
  },
  // {
  //   id: "SUN-50K-G-LV",
  //   title: "Deye 50kW Three Phase String Inverter (Low Voltage)",
  //   model: "SUN-16K-SG01LP1-EU",
  //   srp: "180000",
  //   installer: "150000",
  //   size: "16kW",
  //   imageUrl: "/deye.png",
  //   brandUrl: "/brand-deye.png",
  //   buttonText: "View details",
  //   redirectLink: "/products/inverters/SUN-16K-SG01LP1-EU",
  //   maxPower: "32000",
  //   maxVoltage: "500",
  //   startUp: "125",
  //   ratedVoltage: "370",
  //   maxCurrent: "26+26+26",
  //   maxIsc: "44+44+44",
  //   mppt: "3/2+2+2",
  //   dimensions: "464×763×282",
  //   weight: "52",
  //   datasheet:
  //     "https://drive.google.com/file/d/132cL3o0V_ojNmkpS_1ZuJJVocea8LqbU/view?usp=sharing",
  // },
  {
    id: "LXP-6KMG",
    title: "LuxPower 6kW Hybrid Inverter Single Phase",
    model: "LXP-6KMG",
    srp: "56000",
    installer: "50000",
    size: "6kW",
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/LXP-6KMG",
    maxPower: "",
    maxVoltage: "",
    startUp: "",
    ratedVoltage: "",
    maxCurrent: "",
    maxIsc: "",
    mppt: "",
    dimensions: "",
    weight: "",
    datasheet: "",
  },
  {
    id: "GEN-LB-EU-8K",
    title: "New GEN LuxPower 8kW Hybrid Inverter Single Phase",
    model: "GEN-LB-EU-8K",
    srp: "89000",
    installer: "86000",
    size: "8kW",
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/GEN-LB-EU-8K",
    maxPower: "12000",
    maxVoltage: "500",
    startUp: "140",
    ratedVoltage: "360",
    maxCurrent: "25+25+25",
    maxIsc: "34+34+34",
    mppt: "2/2+2",
    dimensions: "536*556*290mm/21.1*21.9*11.4inch",
    weight: "42.64kg/94lbs",
    datasheet:
      "https://drive.google.com/file/d/1Rx6Zo4opbOSHFHMJ7zGwjJfyYMYvJowB/view?usp=sharing",
  },
  {
    id: "GEN-LB-EU-10K",
    title: "New GEN LuxPower 10kW Hybrid Inverter Single Phase",
    model: "GEN-LB-EU-10K",
    srp: "96000",
    // installer: "81000",
    size: "10kW",
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/GEN-LB-EU-10K",
    maxPower: "15000",
    maxVoltage: "500",
    startUp: "140",
    ratedVoltage: "360",
    maxCurrent: "25+25+25",
    maxIsc: "34+34+34",
    mppt: "2/2+2",
    dimensions: "536*556*290mm/21.1*21.9*11.4inch",
    weight: "42.64kg/94lbs",
    datasheet:
      "https://drive.google.com/file/d/1Rx6Zo4opbOSHFHMJ7zGwjJfyYMYvJowB/view?usp=sharing",
  },
  {
    id: "LXP-LB-EU-12K",
    title: "LuxPower 12kW Hybrid Inverter Single Phase",
    model: "LXP-LB-EU-12K",
    srp: "99000",
    installer: "96000",
    size: "12kW",
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/LXP-LB-EU-12K",
    maxPower: "18000",
    maxVoltage: "500",
    startUp: "140",
    ratedVoltage: "360",
    maxCurrent: "25+15+15",
    maxIsc: "31+19+19",
    mppt: "3/2+1+1",
    dimensions: "490*670*265mm/19.3*26.3*10.4inch",
    weight: "50kg/110.2lbs",
    datasheet:
      "https://drive.google.com/file/d/1VbBZTBxAGhhMMI_FH6kCRp3DSXRRbEQV/view?usp=sharing",
  },
];

export const GridTiedInverterProducts = [
  {
    id: "SUN-6K-G05P1-EU-AM2",
    title: "Deye 6kW Grid-tied Inverter Single Phase",
    model: "SUN-6K-G05P1-EU-AM2",
    srp: "35000",
    installer: "30000",
    size: "6kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-6K-G05P1-EU-AM2",
    maxPower: "9000",
    maxVoltage: "550",
    startUp: "80",
    ratedVoltage: "360",
    maxCurrent: "18+18",
    maxIsc: "27+27",
    mppt: "2/1+1",
    dimensions: "305×280×180",
    weight: "7.7kg",
    datasheet:
      "https://drive.google.com/file/d/10kQ1GhG4miIINXk2Q6LOP0BWxGZENu23/view?usp=drive_link",
  },
  {
    id: "DEYE-GRIDTIED-10KW",
    title: "Deye 10kW Grid-tied Inverter Single Phase",
    model: "SUN-10K-G02P1-EU-AM2",
    srp: "50000",
    installer: "42000",
    size: "10kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/DEYE-GRIDTIED-10KW",
    maxPower: "15000",
    maxVoltage: "550",
    startUp: "80",
    ratedVoltage: "360",
    maxCurrent: "26+26",
    maxIsc: "39+39",
    mppt: "2/2+2",
    dimensions: "330×410×213.5mm",
    weight: "14.8kg",
    datasheet:
      "https://drive.google.com/file/d/10PkAbRPLO3NUPXA7AZTsGXRL7c5de-Rh/view?usp=sharing",
  },
  {
    id: "SUNWAYS-GRIDTIED-3KW",
    title: "Sunways 3kW Grid-tied Inverter Single Phase",
    model: "STS-3KTL-S",
    srp: "21500",
    size: "3kW",
    imageUrl: "/sunways-3kw.png",
    brandUrl: "/brand-sunways.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUNWAYS-GRIDTIED-3KW",
    maxPower: "3,900",
    maxVoltage: "500",
    startUp: "60",
    ratedVoltage: "360",
    maxCurrent: "12.5+12.5",
    maxIsc: "15+15",
    mppt: "1/1",
    dimensions: "327×297×114mm",
    weight: "6.5kg",
    datasheet:
      "https://drive.google.com/file/d/13OHFUiuLJpccJY2UC97MeI985DqG5iDG/view?usp=drive_link",
  },
  {
    id: "SUNWAYS-GRIDTIED-5KW",
    title: "Sunways 5kW Grid-tied Inverter Single Phase",
    model: "STS-5KTL-P",
    srp: "27000",
    size: "5kW",
    imageUrl: "/sunways-3kw.png",
    brandUrl: "/brand-sunways.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUNWAYS-GRIDTIED-5KW",
    maxPower: "8,000",
    maxVoltage: "600",
    startUp: "80",
    ratedVoltage: "360",
    maxCurrent: "15+15",
    maxIsc: "20+20",
    mppt: "2/1+1",
    dimensions: "410×360×120mm",
    weight: "13kg",
    datasheet:
      "https://drive.google.com/file/d/137gAdmetw9RDxqPq6irfjW8Kd6rRIy0G/view?usp=drive_link",
  },
  {
    id: "SUNWAYS-GRIDTIED-6KW",
    title: "Sunways 6kW Grid-tied Inverter Single Phase",
    model: "STS-6KTL-P",
    srp: "28500",
    size: "6kW",
    imageUrl: "/sunways-3kw.png",
    brandUrl: "/brand-sunways.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUNWAYS-GRIDTIED-6KW",
    maxPower: "9,600",
    maxVoltage: "600",
    startUp: "80",
    ratedVoltage: "360",
    maxCurrent: "15+15",
    maxIsc: "20+20",
    mppt: "2/1+1",
    dimensions: "410x360x120mm",
    weight: "13kg",
    datasheet:
      "https://drive.google.com/file/d/137gAdmetw9RDxqPq6irfjW8Kd6rRIy0G/view?usp=drive_link",
  },
  {
    id: "SUNWAYS-GRIDTIED-8KW",
    title: "Sunways 8kW Grid-tied Inverter Single Phase",
    model: "STS-8KTL",
    srp: "41000",
    size: "8kW",
    imageUrl: "/sunways-3kw.png",
    brandUrl: "/brand-sunways.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUNWAYS-GRIDTIED-8KW",
    maxPower: "12,800",
    maxVoltage: "600",
    startUp: "80",
    ratedVoltage: "360",
    maxCurrent: "15+30",
    maxIsc: "20+40",
    mppt: "2/1+2",
    dimensions: "550x410x75mm",
    weight: "24kg",
    datasheet:
      "https://drive.google.com/file/d/13Prz4AUJSLBNVTlaRXb5NUMSSFqCee2f/view?usp=sharing",
  },
  {
    id: "SUNWAYS-GRIDTIED-10KW",
    title: "Sunways 10kW Grid-tied Inverter Single Phase",
    model: "STS-10KTL",
    srp: "45000",
    size: "10kW",
    imageUrl: "/sunways-3kw.png",
    brandUrl: "/brand-sunways.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUNWAYS-GRIDTIED-8KW",
    maxPower: "16,000",
    maxVoltage: "600",
    startUp: "80",
    ratedVoltage: "360",
    maxCurrent: "15+30",
    maxIsc: "20+40",
    mppt: "2/1+2",
    dimensions: "550x410x75mm",
    weight: "26g",
    datasheet:
      "https://drive.google.com/file/d/13Prz4AUJSLBNVTlaRXb5NUMSSFqCee2f/view?usp=sharing",
  },
  {
    id: "SOLIS-GRIDTIED-50KW-LV",
    title: "Solis 50kW Grid-tied Inverter Single Phase",
    model: "Solis-50K-LV-5G",
    srp: "250000",
    size: "50kW",
    imageUrl: "/solis-50k.webp",
    brandUrl: "/brand-solis.webp",
    buttonText: "View details",
    redirectLink: "/products/inverters/SOLIS-GRIDTIED-50KW-LV",
    maxVoltage: "1,100",
    startUp: "195",
    ratedVoltage: "450",
    maxCurrent: "6*26",
    maxIsc: "6*40",
    mppt: "6/12",
    dimensions: "1065×567×344.5mm",
    weight: "81kg",
    datasheet:
      "https://drive.google.com/file/d/1_r5SED-MWqpZgIE3Bp-pbaDtKOKF7qe8/view?usp=drive_link",
  },
];

export const PanelProducts = [
  {
    id: "SRP-550-BMA-HV",
    title: "Seraphim 550W Black Frame",
    model: "SRP-550-BMA-HV",
    srp: "4500",
    installer: "4400",
    size: "550W",
    imageUrl: "/seraphim550.png",
    brandUrl: "/brand-seraphim.png",
    buttonText: "View details",
    redirectLink: "/products/panels/SRP-550-BMA-HV",
    datasheetLink:
      "https://drive.google.com/file/d/13R47Sf3z-x7uFlWAUzC_grNzVWn0OU69/view?usp=sharing",
    solarCells: "PERC Mono (144pcs)",
    dimensions: "2278 x 1134 x 30 mm",
    weight: "26.5 kg",
    vmp: "42.05",
    imp: "13.08",
    voc: "49.70",
    isc: "14.00",
    efficiency: "21.29",
  },
  {
    id: "SRP-580-BTA-BG",
    title: "Seraphim 580W Bifacial",
    model: "SRP-580-BTA-BG",
    srp: "5000",
    installer: "4700",
    size: "580W",
    imageUrl: "/seraphim580.png",
    brandUrl: "/brand-seraphim.png",
    buttonText: "View details",
    redirectLink: "/products/panels/SRP-580-BTA-BG",
    datasheetLink:
      "https://drive.google.com/file/d/1gX8mryzB1i03Es-6GrX7H22LQWMJFhAx/view?usp=sharing",
    solarCells: "N-TOPCon 182 x 91mm (144pcs)",
    dimensions: "2278 x 1134 x 30 mm",
    weight: "32.0 kg",
    vmp: "43.4",
    imp: "13.37",
    voc: "52.1",
    isc: "14.07",
    efficiency: "22.45",
  },
  {
    id: "AE550MD-144",
    title: "AE Solar 550W",
    model: "AE550MD-144",
    srp: "4800",
    installer: "4400",
    size: "550W",
    imageUrl: "/ae.png",
    brandUrl: "/brand-ae.png",
    buttonText: "View details",
    redirectLink: "/products/panels/AE550MD-144",
    datasheetLink:
      "https://drive.google.com/file/d/19_YvI9cJfbHrzqdt6hvcAKBMfv0xlFtj/view?usp=sharing",
    solarCells: "Gallium-doped Mono c-Si PERC, Half-cut cells, 182 mm",
    dimensions: "2278 mm x 1133 mm x 30 mm",
    weight: "26.5 kg",
    vmp: "42.57",
    imp: "12.92",
    voc: "51.44",
    isc: "13.67",
    efficiency: "21.31",
  },
  {
    id: "AE580ME-120BS",
    title: "AE Solar 580W",
    model: "AE580CMD-144",
    srp: "5000",
    installer: "4500",
    size: "580W",
    imageUrl: "/ae.png",
    brandUrl: "/brand-ae.png",
    buttonText: "View details",
    redirectLink: "/products/panels/AE580ME-120BS",
    datasheetLink:
      "https://drive.google.com/file/d/11u6w6DSJOT6S_TT25tLIAYsOom1xajpi/view?usp=drive_link",
    solarCells: "n-Type TOPCon technology, half-cut cells",
    dimensions: "2278 mm x 1133 mm x 30 mm",
    weight: "26.5 kg",
    vmp: "43.04",
    imp: "13.49",
    voc: "50.86",
    isc: "14.4",
    efficiency: "22.47",
  },
  {
    id: "TSM-DE18M-500W",
    title: "Trina 500W",
    model: "TSM-DE18M(II)",
    srp: "4600",
    installer: "4400",
    size: "500W",
    imageUrl: "/trina.png",
    brandUrl: "/brand-trina.png",
    buttonText: "View details",
    redirectLink: "/products/panels/TSM-DE18M-500W",
    datasheetLink:
      "https://drive.google.com/file/d/1-li6O74kuhnE3g9EM6T6XbxsNVGTtyKc/view?usp=drive_link",
    solarCells: "Monocrystalline",
    dimensions: "2176 ×1098× 35 mm (85.67 × 43.23 × 1.38 inches)",
    weight: "26.3 kg (58.0 lb)",
    vmp: "42.8",
    imp: "11.69",
    voc: "51.7",
    isc: "12.28",
    efficiency: "20.9",
  },
  {
    id: "TSM-DE18-550W",
    title: "Trina 550W",
    model: "TSM-DE18",
    srp: "4700",
    installer: "4500",
    size: "550W",
    imageUrl: "/trina.png",
    brandUrl: "/brand-trina.png",
    buttonText: "View details",
    redirectLink: "/products/panels/TSM-DE18-550W",
    datasheetLink:
      "https://drive.google.com/file/d/1ti8lF7Mi0o000vxSzdbRbDjw2MTJnZ0-/view?usp=sharing",
    solarCells: "Monocrystalline",
    dimensions: "2278×1134×35 mm (89.69×44.65×1.38 inches)",
    weight: "27.8 kg (61.3 lb)",
    vmp: "41.6",
    imp: "13.21",
    voc: "49.8",
    isc: "14.02",
    efficiency: "21.3",
  },
  {
    id: "TSM-NEG19RC-610W",
    title: "Trina 610W",
    model: "TSM-NEG19RC.20",
    srp: "5900",
    installer: "5700",
    size: "610W",
    imageUrl: "/trina.png",
    brandUrl: "/brand-trina.png",
    buttonText: "View details",
    redirectLink: "/products/panels/TSM-NEG19RC-610W",
    datasheetLink:
      "https://drive.google.com/file/d/1-kJM57_Q9dlwjdBx9KM9H3B1C-O_jKDS/view?usp=drive_link",
    solarCells: "N-type Monocrystalline",
    dimensions: "2382×1134×30 mm (93.78×44.65×1.18 inches)",
    weight: "33.7kg (74.3 lb)",
    vmp: "40.8",
    imp: "14.96",
    voc: "49",
    isc: "15.86",
    efficiency: "22.6",
  },
];

export const BatteryProducts = [
  {
    id: "ATE-48V-200AH",
    title: "AllTopElec 51.2V 200Ah LiFePO4 Battery",
    brand: "AllTopElec",
    model: "ATE-48V-200AH",
    srp: "90000",
    installer: "80000",
    size: "10kWh",
    imageUrl: "/ate.png",
    brandUrl: "/brand-ate.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/ATE-48V-200AH",
    batteryType: "LiFePO4",
    batteryEnergy: "10.24kWh",
    nominalCapacity: "200Ah",
    nominalVoltage: "51.2V",
    dod: "90%",
    weight: "90kg",
    dimension: "226*550*700mm",
    communication: "CAN/RS485/RS232",
    datasheet:
      "https://drive.google.com/file/d/1MKCA6zmlxBCrQx8V50iGaNxYwGsF2TbM/view?usp=sharing",
  },
  {
    id: "ATE-48V-300AH",
    title: "AllTopElec 51.2V 300Ah LiFePO4 Battery",
    brand: "AllTopElec",
    model: "ATE-48V-300AH",
    srp: "120000",
    installer: "115000",
    size: "15kWh",
    imageUrl: "/ate.png",
    brandUrl: "/brand-ate.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/ATE-48V-300AH",
    batteryType: "LiFePO4",
    batteryEnergy: "15.36kWh",
    nominalCapacity: "300Ah",
    nominalVoltage: "51.2V",
    dod: "90%",
    weight: "125kg",
    dimension: "262*465*758mm",
    communication: "CAN/RS485/RS232",
    datasheet:
      "https://drive.google.com/file/d/15qK3i-96kKJ_srHQsQoV1rmMFGRk4wCk/view?usp=drive_link",
  },
  {
    id: "BX51100",
    title: "Dyness 51.2V 100Ah LiFePO4 Battery",
    brand: "Dyness",
    model: "BX51100",
    srp: "53000",
    installer: "50000",
    size: "5kWh",
    imageUrl: "/dyness.png",
    brandUrl: "/brand-dyness.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/BX51100",
    batteryType: "LiFePO4",
    batteryEnergy: "5.12 kWh",
    nominalCapacity: "100Ah",
    nominalVoltage: "51.2V",
    dod: "90%",
    weight: "50kg",
    dimension: "558*545*150mm",
    communication: "CAN/RS485/RS232",
    datasheet:
      "https://drive.google.com/file/d/1GdwVUr58WhdQiIvwQfJ8_qjP1UkkgwtL/view?usp=drive_link",
  },
  {
    id: "DYN-PW-F-10-PRO",
    title: "Dyness 51.2V 200Ah LiFePO4 Battery",
    brand: "Dyness",
    model: "DYN-PW-F-10.0 PRO",
    srp: "135000",
    installer: "125000",
    size: "10kWh",
    imageUrl: "/dyness-200.png",
    brandUrl: "/brand-dyness.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/DYN-PW-F-10-PRO",
    batteryType: "LiFePO4",
    batteryEnergy: "10.24kWh",
    nominalCapacity: "200Ah",
    nominalVoltage: "51.2V",
    dod: "90%",
    weight: "115kg",
    dimension: "555*210*1020mm",
    communication: "CAN/RS485/RS232",
    datasheet:
      "https://drive.google.com/file/d/1JaCThCyqyqxT4FFelwURE7y-48Fp9QML/view?usp=sharing",
  },
  {
    id: "LFRX51100-01",
    title: "LVFU 51.2V 100Ah LiFePO4 Battery",
    brand: "LVFU",
    model: "LFRX51100-01",
    srp: "50000",
    installer: "45000",
    size: "5kWh",
    imageUrl: "/lvfu.png",
    brandUrl: "/brand-lvfu.webp",
    buttonText: "View details",
    redirectLink: "/products/batteries/LFRX51100-01",
    batteryType: "LiFePO4",
    batteryEnergy: "5.12 kWh",
    nominalCapacity: "100Ah",
    nominalVoltage: "51.2V",
    dod: "90%",
    weight: "50kg",
    dimension: "484 x 410 x 178 mm",
    communication: "CAN/RS485/RS232",
    datasheet:
      "https://drive.google.com/file/d/1mvjLtwUASCw53g8KhdbyxZEDbT3ZBgUc/view?usp=sharing",
  },
  {
    id: "LFRX51200-01",
    title: "LVFU 51.2V 200Ah LiFePO4 Battery",
    brand: "LVFU",
    model: "LFRX51200-01",
    srp: "90000",
    installer: "80000",
    size: "10kWh",
    imageUrl: "/lvfu.png",
    brandUrl: "/brand-lvfu.webp",
    buttonText: "View details",
    redirectLink: "/products/batteries/LFRX51200-01",
    batteryType: "LiFePO4",
    batteryEnergy: "10.24kWh",
    nominalCapacity: "200Ah",
    nominalVoltage: "51.2V",
    dod: "90%",
    weight: "90kg",
    dimension: "484 x 590 x 178 mm",
    communication: "CAN/RS485/RS232",
    datasheet:
      "https://drive.google.com/file/d/1mvjLtwUASCw53g8KhdbyxZEDbT3ZBgUc/view?usp=sharing",
  },
  // {
  //   id: "Wipuvo-48V-300AH",
  //   title: "Wipuvo 51.2V 300Ah LiFePO4 Battery",
  //   brand: "Wipuvo",
  //   model: "Wipuvo-48V-300AH",
  //   srp: "125000",
  //   installer: "120000",
  //   size: "15kWh",
  //   imageUrl: "/wipuvo.png",
  //   brandUrl: "/brand-wipuvo.png",
  //   buttonText: "View details",
  //   redirectLink: "/products/batteries/Wipuvo-48V-200AH",
  //   batteryType: "LiFePO4",
  //   batteryEnergy: "15.36kWh",
  //   nominalCapacity: "300Ah",
  //   nominalVoltage: "51.2V",
  //   dod: "",
  //   weight: "",
  //   dimension: "",
  //   communication: "",
  //   datasheet: "",
  // },
];
