import {
  Award,
  Bulb,
  HeartHandshake,
  Settings,
  Tree,
  Users,
} from "tabler-icons-react";

export const HybridDIYPackages = [
  {
    title: "5kW Hybrid DIY Package",
    description: `includes a 5kW hybrid inverter, 5.5kWp solar panels, 10kWh LiFePO4 battery, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting)`,
    price: "Starts at Php 242,535 (VAT Exclusive)",
    imageUrl: "/package.png",
    buttonText: "Get a Quote",
    redirectLink: "/quotation?type=hybrid&system=5kW",
  },
  {
    title: "6kW Hybrid DIY Package",
    description: `includes a 6kW hybrid inverter, 6.05kWp solar panels, 10kWh LiFePO4 battery, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting)`,
    price: "Starts at Php 254,000 (VAT Exclusive)",
    imageUrl: "/package.png",
    buttonText: "Get a Quote",
    redirectLink: "/quotation?type=hybrid&system=6kW",
  },

  {
    title: "8kW Hybrid DIY Package",
    description: `includes a 8kW hybrid inverter, 8.25kWp solar panels, 10kWh LiFePO4 battery, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting)`,
    price: "Starts at Php 316,650 (VAT Exclusive)",
    imageUrl: "/package.png",
    buttonText: "Get a Quote",
    redirectLink: "/quotation?type=hybrid&system=8kW",
  },

  {
    title: "12kW Hybrid DIY Package",
    description: `includes a 12kW hybrid inverter, 11.6kWp solar panels, 15kWh LiFePO4 battery, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting)`,
    price: "Starts at Php 424,550 (VAT Exclusive)",
    imageUrl: "/package.png",
    buttonText: "Get a Quote",
    redirectLink: "/quotation?type=hybrid&system=12kW",
  },

  {
    title: "16kW Hybrid DIY Package",
    description: `includes a 16kW hybrid inverter, 15.6kWp solar panels, 15kWh LiFePO4 battery, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting)`,
    price: "Starts at Php 515,530 (VAT Exclusive)",
    imageUrl: "/package.png",
    buttonText: "Get a Quote",
    redirectLink: "/quotation?type=hybrid&system=16kW",
  },
];

export const GridTiedDIYPackages = [
  {
    title: "6kW Grid-tied DIY Package",
    description: `includes a 6kW grid-tied inverter, 6.6kWp solar panels, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting) (Note: Net Metering not Included)`,
    price: "Starts at Php 152,240 (VAT Exclusive)",
    imageUrl: "/package-gridtied.png",
    buttonText: "Get a Quote",
    redirectLink: "/quotation?type=gridtied&system=6kW",
  },
  {
    title: "10kW Grid-tied DIY Package",
    description: `includes a 10kW grid-tied inverter, 10.44kWp solar panels, mounting system, safety devices, and all necessary cables and accessories. FREE Technical Support (PV System Design, Parameter Settings & Troubleshooting) (Note: Net Metering not Included)`,
    price: "Starts at Php 216,330 (VAT Exclusive)",
    imageUrl: "/package-gridtied.png",
    buttonText: "Get a Quote",
    redirectLink: "/quotation?type=gridtied&system=10kW",
  },
];

export const ServicesData = [
  {
    title: "PV SYSTEM DESIGN",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "FULL INSTALLATION",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "PROCUREMENT",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "MAINTENANCE",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "PROJECT MANAGEMENT",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "PROJECT CONSULTATION",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "TROUBLESHOOTING AND TECHNICAL SUPPORT",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "EXCLUSIVE MENTORING",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
  {
    title: "TRAINING AND SEMINARS",
    description: `Professional and efficient installation services ensuring optimal performance and longevity of your solar systems.`,
    imageUrl: "/package.png",
  },
];

export const JFLTeamMembers = [
  {
    imageUrl: "/team-jf.jpg",
    name: "JF Legaspi",
    position: "CEO / Founder",
    description: `"A visionary leader with extensive experience in the global solar industry, committed to advancing renewable energy solutions in the Philippines."`,
  },
  {
    imageUrl: "/team-john.jpg",
    name: "John Bergueles",
    position: "CCO (Sales and Marketing)",
    description: `"A dynamic strategist driving business growth through effective sales initiatives and impactful marketing campaigns."`,
  },
  {
    imageUrl: "/team-jay.jpg",
    name: "Jay Escander",
    position: "CTO",
    description: `"An innovative technical expert specializing in designing and implementing efficient and reliable solar PV systems."`,
  },
];

export const FeaturesData = [
  {
    title: "European Quality Standards",
    description: `We adhere to stringent European quality benchmarks, ensuring superior workmanship and durable solutions.`,
    icon: Award,
  },
  {
    title: "Expertise and Experience",
    description: `Our team brings international experience and deep technical knowledge, guaranteeing innovative and effective solutions.`,
    icon: Bulb,
  },
  {
    title: "Comprehensive Services",
    description: `From procurement to maintenance, we offer end-to-end services tailored to meet diverse energy needs.`,
    icon: Settings,
  },
  {
    title: "Customer-Centric Approach",
    description: `We prioritize our clients' satisfaction, offering personalized services and ongoing support throughout your solar journey.`,
    icon: Users,
  },
  {
    title: "Technical Support for DIY Enthusiasts",
    description: `Our team brings international experience and deep technical knowledge, guaranteeing innovative and effective solutions.`,
    icon: HeartHandshake,
  },
  {
    title: "Commitment to Sustainability",
    description: `Our solutions are designed to promote environmental stewardship and contribute to a sustainable future.`,
    icon: Tree,
  },
];

export const HybridInverterProducts = [
  {
    title: "Deye 5kW Hybrid Inverter Single Phase",
    model: "SUN-SG03LP1-EU",
    srp: 55000,
    installer: 51000,
    size: "5kW",
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG03LP1-EU-5KW",
  },
  {
    title: "Deye 6kW Hybrid Inverter Single Phase",
    model: "SUN-SG03LP1-EU",
    srp: 56000,
    installer: 53000,
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    size: "6kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG03LP1-EU-6KW",
  },
  {
    title: "Deye 8kW Hybrid Inverter Single Phase",
    model: "SUN-SG01LP1-EU",
    srp: 87000,
    installer: 85000,
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    size: "8kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG01LP1-EU-8KW",
  },
  {
    title: "Deye 12kW Hybrid Inverter Single Phase",
    model: "SUN-SG01LP1-EU",
    srp: 145000,
    installer: 130000,
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    size: "12kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG01LP1-EU-12KW",
  },
  {
    title: "Deye 16kW Hybrid Inverter Single Phase",
    model: "SUN-SG01LP1-EU",
    srp: 160000,
    installer: 150000,
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    size: "16kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG01LP1-EU-16KW",
  },
  {
    title: "LuxPower 6kW Hybrid Inverter Single Phase",
    model: "LXP-6KMG",
    srp: 49000,
    installer: 44000,
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    size: "6kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG03LP1-EU-6KW",
  },
  {
    title: "New GEN LuxPower 8kW Hybrid Inverter Single Phase",
    model: "GEN-LB-EU-8K",
    srp: 105000,
    installer: 83000,
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    size: "8kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/GEN-LB-EU-8K",
  },
  {
    title: "New GEN LuxPower 10kW Hybrid Inverter Single Phase",
    model: "GEN-LB-EU-10K",
    srp: 115000,
    installer: 96500,
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    size: "10kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/GEN-LB-EU-10K",
  },
  {
    title: "LuxPower 12kW Hybrid Inverter Single Phase",
    model: "LXP-LB-EU-12K",
    srp: 112000,
    installer: 103000,
    imageUrl: "/lxp.png",
    brandUrl: "/brand-lxp.png",
    size: "12kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/LXP-LB-EU-12K",
  },
];

export const GridTiedInverterProducts = [
  {
    title: "Deye 6kW Grid-tied Inverter Single Phase",
    model: "SUN-SG03LP1-EU",
    srp: 35000,
    installer: 30000,
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    size: "6kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG03LP1-EU-5KW",
  },
  {
    title: "Deye 10kW Hybrid Inverter Single Phase",
    model: "SUN-SG03LP1-EU",
    srp: 50000,
    installer: 42000,
    imageUrl: "/deye.png",
    brandUrl: "/brand-deye.png",
    size: "10kW",
    buttonText: "View details",
    redirectLink: "/products/inverters/SUN-SG03LP1-EU-6KW",
  },
];
export const PanelProducts = [
  {
    title: "Seraphim 580W Bifacial",
    model: "SRP-580-BTA-BG",
    srp: 5000,
    installer: 4700,
    size: "580W",
    imageUrl: "/seraphim580.png",
    brandUrl: "/brand-seraphim.png",
    buttonText: "View details",
    redirectLink: "/products/panels/SRP-580-BTA-BG",
  },
  {
    title: "AE Solar 550W",
    model: "AE550MD-144",
    srp: 4800,
    installer: 4400,
    size: "550W",
    imageUrl: "/ae.png",
    brandUrl: "/brand-ae.png",
    buttonText: "View details",
    redirectLink: "/products/panels/AE550MD-144",
  },
  {
    title: "AE Solar 580W",
    model: "AE580ME-120BS",
    srp: 5000,
    installer: 4500,
    size: "580W",
    imageUrl: "/ae.png",
    brandUrl: "/brand-ae.png",
    buttonText: "View details",
    redirectLink: "/products/panels/AE580ME-120BS",
  },
  {
    title: "Trina 500W",
    model: "trina500W",
    srp: 4600,
    installer: 4400,
    size: "500W",
    imageUrl: "/trina.png",
    brandUrl: "/brand-trina.png",
    buttonText: "View details",
    redirectLink: "/products/panels/trina500W",
  },
  {
    title: "Trina 550W",
    model: "trina550W",
    srp: 4700,
    installer: 4500,
    size: "550W",
    imageUrl: "/trina.png",
    brandUrl: "/brand-trina.png",
    buttonText: "View details",
    redirectLink: "/products/panels/trina550W",
  },
  {
    title: "Trina 610W",
    model: "trina610W",
    srp: 5900,
    installer: 5700,
    size: "610W",
    imageUrl: "/trina.png",
    brandUrl: "/brand-trina.png",
    buttonText: "View details",
    redirectLink: "/products/panels/trina610W",
  },
];

export const BatteryProducts = [
  {
    title: "AllTopElec 51.2V 200Ah LiFePO4 Battery",
    model: "ATE-48V-200AH",
    srp: 90000,
    installer: 80000,
    size: "10kWh",
    imageUrl: "/ate.png",
    brandUrl: "/brand-ate.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/ATE-48V-200AH",
  },
  {
    title: "AllTopElec 51.2V 300Ah LiFePO4 Battery",
    model: "ATE-48V-300AH",
    srp: 120000,
    installer: 115000,
    size: "15kWh",
    imageUrl: "/ate.png",
    brandUrl: "/brand-ate.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/ATE-48V-300AH",
  },
  {
    title: "Dyness 51.2V 100Ah LiFePO4 Battery",
    model: "Dyness-48V-100AH",
    srp: 53000,
    installer: 50000,
    size: "5kWh",
    imageUrl: "/dyness.png",
    brandUrl: "/brand-dyness.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/Dyness-48V-100AH",
  },
  {
    title: "Dyness 51.2V 200Ah LiFePO4 Battery",
    model: "Dyness-48V-200AH",
    srp: 135000,
    installer: 125000,
    size: "10kWh",
    imageUrl: "/dyness.png",
    brandUrl: "/brand-dyness.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/Dyness-48V-200AH",
  },
  {
    title: "LVFU 51.2V 100Ah LiFePO4 Battery",
    model: "LVFU-48V-100AH",
    srp: 50000,
    installer: 45000,
    size: "5kWh",
    imageUrl: "/lvfu.png",
    brandUrl: "/brand-lvfu.webp",
    buttonText: "View details",
    redirectLink: "/products/batteries/LVFU-48V-100AH",
  },
  {
    title: "LVFU 51.2V 200Ah LiFePO4 Battery",
    model: "LVFU-48V-200AH",
    srp: 90000,
    installer: 80000,
    size: "10kWh",
    imageUrl: "/lvfu.png",
    brandUrl: "/brand-lvfu.webp",
    buttonText: "View details",
    redirectLink: "/products/batteries/LVFU-48V-200AH",
  },
  {
    title: "Wipuvo 51.2V 300Ah LiFePO4 Battery",
    model: "Wipuvo-48V-300AH",
    srp: 125000,
    installer: 120000,
    size: "15kWh",
    imageUrl: "/wipuvo.png",
    brandUrl: "/brand-wipuvo.png",
    buttonText: "View details",
    redirectLink: "/products/batteries/Wipuvo-48V-200AH",
  },
];
